# Generated by Django 4.1.7 on 2023-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotionalGreeks',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bid', models.FloatField()),
                ('quote_datetime', models.DateTimeField()),
                ('expiration', models.DateField()),
                ('option_type', models.BooleanField()),
                ('strike', models.FloatField()),
                ('o_open', models.FloatField()),
                ('o_high', models.FloatField()),
                ('o_low', models.FloatField()),
                ('o_close', models.FloatField()),
                ('trade_volume', models.IntegerField()),
                ('bid_size', models.IntegerField()),
                ('ask_size', models.IntegerField()),
                ('ask', models.FloatField()),
                ('underlying_bid', models.FloatField()),
                ('underlying_ask', models.FloatField()),
                ('implied_underlying_price', models.FloatField()),
                ('active_underlying_price', models.FloatField()),
                ('implied_volatility', models.FloatField()),
                ('delta', models.FloatField()),
                ('gamma', models.FloatField()),
                ('theta', models.FloatField()),
                ('vega', models.FloatField()),
                ('rho', models.FloatField()),
                ('oi', models.IntegerField()),
            ],
            options={
                'db_table': 'dev_spxw_data',
                'managed': False,
            },
        ),
    ]
